# Generated by Django 3.2.4 on 2021-06-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('chart_id', models.AutoField(primary_key=True, serialize=False)),
                ('chart_function', models.CharField(max_length=40)),
                ('chart_interval', models.IntegerField()),
                ('chart_step', models.IntegerField()),
                ('chart_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('processing_date', models.CharField(max_length=50)),
            ],
        ),
    ]
