# Generated by Django 3.2.4 on 2021-06-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FunctionsDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='processing_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
