# Generated by Django 3.2.4 on 2021-06-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FunctionsDashboard', '0002_alter_chart_processing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='processing_date',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
